[build]
  # Répertoire de base pour le build
  base = "frontend-clean/frontend"
  # Commande de build pour Vue.js
  command = "npm install --include=dev && npm run build"
  # Répertoire où sont les fichiers buildés
  publish = "dist"
  # Répertoire des fonctions Netlify (équivalent du dossier /api de Vercel)
  functions = "../../netlify/functions"

[build.environment]
  # Version Node.js
  NODE_VERSION = "20"
  # Force clean install
  NPM_FLAGS = "--legacy-peer-deps"
  # Disable cache pour forcer installation complète
  NETLIFY_SKIP_CACHE = "true"

# Priorité: route contact -> nouvelle fonction contact2
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact2"
  status = 200

# Route dédiée contact2
[[redirects]]
  from = "/api/contact2"
  to = "/.netlify/functions/contact2"
  status = 200

# Générique API -> functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Uploads -> function uploads (fichiers/avatars)
[[redirects]]
  from = "/uploads/*"
  to = "/.netlify/functions/uploads/:splat"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Plugin pour installer automatiquement les dépendances des fonctions
[[plugins]]
package = "@netlify/plugin-functions-install-core"

# Variables d'environnement (à configurer via l'interface Netlify)
# MONGODB_URI, JWT_SECRET, JWT_ISSUER, JWT_AUDIENCE